# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 469ce5ea5d0bacd327ff4e26ee5875c796cc230c5776dc2eea5c62668aaab4504b7cc736110fda7f79b9ab86719dbc5be289b1181568782da02d14a1f79d5606

test:
  secret_key_base: f53377b5d3098775fa5b667bd376e9aadac10fdbc7f3b3ba2a431057d8ffea35c8d7b58a14eadb598a07c423455382d2564fc532a3246247c8217a1f35aa180a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
